name: Go Release
on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: actions-go-release
      uses: RomanosTrechlis/actions-go-release@v1.0
      with:
        # Release's name
        release_name: shoelaces
        # Go's target operating system
        goos: linux
        # Go's target architecture
        goarch: amd64