name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  go:
    uses: estenrye/github-actions/.github/workflows/golang-build-and-test.yml@v0.1.0

  docker:
    uses: estenrye/github-actions.github/workflows/docker-multiarch-build-and-push.yml@v0.1.0
    with:
      push: false
      image_name: shoelaces
      registry_username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
      registry_password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}